#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

import chromadb
from sentence_transformers import SentenceTransformer

def load_chunks(chunks_path: Path) -> list[dict]:
    rows = []
    with chunks_path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def batched(items: list, batch_size: int):
    for idx in range(0, len(items), batch_size):
        yield items[idx : idx + batch_size]


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def write_postgres_sql_dump(
    chunks: list[dict],
    model_name: str,
    sql_output_path: Path,
    schema: str,
    table: str,
    batch_size: int,
) -> None:
    model = SentenceTransformer(model_name)
    texts = [item.get("text", "") for item in chunks]
    embeddings = model.encode(
        texts,
        batch_size=batch_size,
        normalize_embeddings=True,
        show_progress_bar=True,
    ).tolist()
    dim = len(embeddings[0]) if embeddings else 0
    if dim <= 0:
        raise ValueError("Cannot determine embedding dimension.")

    sql_output_path.parent.mkdir(parents=True, exist_ok=True)
    with sql_output_path.open("w", encoding="utf-8") as handle:
        handle.write("-- PostgreSQL/pgvector compatible dump generated by build_vector_db.py\n")
        handle.write("SET client_encoding TO 'UTF8';\n")
        handle.write("BEGIN;\n")
        handle.write("CREATE EXTENSION IF NOT EXISTS vector;\n")
        handle.write(f"CREATE SCHEMA IF NOT EXISTS {schema};\n")
        handle.write(f"CREATE TABLE IF NOT EXISTS {schema}.{table} (\n")
        handle.write("  chunk_id TEXT PRIMARY KEY,\n")
        handle.write("  doc_id TEXT,\n")
        handle.write("  issue_date TEXT,\n")
        handle.write("  title TEXT,\n")
        handle.write("  chunk_index INTEGER,\n")
        handle.write("  chunk_chars INTEGER,\n")
        handle.write("  text_content TEXT,\n")
        handle.write(f"  embedding vector({dim})\n")
        handle.write(");\n")
        handle.write(
            f"CREATE INDEX IF NOT EXISTS {table}_embedding_idx ON {schema}.{table} USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);\n"
        )
        handle.write(
            f"CREATE INDEX IF NOT EXISTS {table}_issue_date_idx ON {schema}.{table}(issue_date);\n"
        )
        handle.write(
            f"COMMENT ON TABLE {schema}.{table} IS {sql_literal('source=' + str(model_name))};\n"
        )

        for item, emb in zip(chunks, embeddings):
            chunk_id = sql_literal(str(item.get("chunk_id", "")))
            doc_id = sql_literal(str(item.get("doc_id", "")))
            issue_date = sql_literal(str(item.get("issue_date", "")))
            title = sql_literal(str(item.get("title", "")))
            chunk_index = int(item.get("chunk_index", 0))
            chunk_chars = int(item.get("chunk_chars", len(item.get("text", ""))))
            text_content = sql_literal(str(item.get("text", "")))
            emb_literal = sql_literal(json.dumps(emb))

            handle.write(
                f"INSERT INTO {schema}.{table} (chunk_id, doc_id, issue_date, title, chunk_index, chunk_chars, text_content, embedding)\n"
                f"VALUES ({chunk_id}, {doc_id}, {issue_date}, {title}, {chunk_index}, {chunk_chars}, {text_content}, {emb_literal}::vector)\n"
                "ON CONFLICT (chunk_id) DO UPDATE SET\n"
                "  doc_id = EXCLUDED.doc_id,\n"
                "  issue_date = EXCLUDED.issue_date,\n"
                "  title = EXCLUDED.title,\n"
                "  chunk_index = EXCLUDED.chunk_index,\n"
                "  chunk_chars = EXCLUDED.chunk_chars,\n"
                "  text_content = EXCLUDED.text_content,\n"
                "  embedding = EXCLUDED.embedding;\n"
            )

        handle.write("COMMIT;\n")

    print(f"Postgres SQL dump ready: {sql_output_path}")
    print(f"Rows exported: {len(chunks)} | embedding_dim: {dim}")


def build_vector_db(
    chunks_path: Path,
    db_dir: Path,
    collection_name: str,
    model_name: str,
    batch_size: int,
) -> None:
    chunks = load_chunks(chunks_path)
    if not chunks:
        raise ValueError(f"No chunks loaded from: {chunks_path}")

    db_dir.mkdir(parents=True, exist_ok=True)
    client = chromadb.PersistentClient(path=str(db_dir))

    try:
        client.delete_collection(collection_name)
    except Exception:
        pass

    collection = client.create_collection(
        name=collection_name,
        metadata={"source": str(chunks_path), "embedding_model": model_name},
    )

    model = SentenceTransformer(model_name)

    print(f"Loaded chunks: {len(chunks)}")
    print(f"Embedding model: {model_name}")
    print(f"Writing to DB: {db_dir} (collection: {collection_name})")

    for batch in batched(chunks, batch_size):
        ids = [item["chunk_id"] for item in batch]
        docs = [item["text"] for item in batch]
        metas = [
            {
                "doc_id": item.get("doc_id", ""),
                "issue_date": item.get("issue_date", ""),
                "title": item.get("title", ""),
                "chunk_index": int(item.get("chunk_index", 0)),
                "chunk_chars": int(item.get("chunk_chars", len(item.get("text", "")))),
            }
            for item in batch
        ]
        embeddings = model.encode(docs, normalize_embeddings=True).tolist()
        collection.add(ids=ids, documents=docs, metadatas=metas, embeddings=embeddings)

    print(f"Vector DB ready. Total vectors: {collection.count()}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build Chroma DB or PostgreSQL-compatible pgvector SQL dump from chunks JSONL."
    )
    parser.add_argument(
        "--chunks-path",
        default="data/ouch_dataset/processed/chunks.jsonl",
        help="Path to chunks JSONL",
    )
    parser.add_argument(
        "--db-dir",
        default="data/ouch_dataset/vector_db",
        help="Directory for persistent Chroma DB",
    )
    parser.add_argument(
        "--output-type",
        default="postgres-sql",
        choices=["postgres-sql", "chroma"],
        help="Output type to generate",
    )
    parser.add_argument(
        "--sql-output-path",
        default="data/ouch_dataset/vector_db_pg.sql",
        help="PostgreSQL dump file path for --output-type postgres-sql",
    )
    parser.add_argument("--schema", default="vector", help="Postgres schema name")
    parser.add_argument("--table", default="ouch_chunks", help="Postgres table name")
    parser.add_argument(
        "--collection-name",
        default="ouch_chunks_pl",
        help="Chroma collection name",
    )
    parser.add_argument(
        "--model-name",
        default="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
        help="SentenceTransformer model id",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=64,
        help="Embedding batch size",
    )
    args = parser.parse_args()

    chunks = load_chunks(Path(args.chunks_path))
    if not chunks:
        raise ValueError(f"No chunks loaded from: {args.chunks_path}")

    if args.output_type == "postgres-sql":
        write_postgres_sql_dump(
            chunks=chunks,
            model_name=args.model_name,
            sql_output_path=Path(args.sql_output_path),
            schema=args.schema,
            table=args.table,
            batch_size=args.batch_size,
        )
        return

    build_vector_db(
        chunks_path=Path(args.chunks_path),
        db_dir=Path(args.db_dir),
        collection_name=args.collection_name,
        model_name=args.model_name,
        batch_size=args.batch_size,
    )


if __name__ == "__main__":
    main()
